### PR TITLE
Add the processlist command-line option

### PR DESCRIPTION
**Pull request by robinbowes**
$opt{procs} is used in the script, but there is no way to enable it from the command line.

My last commit adds the command line options.

Not sure what all the other stuff is - I pulled those changes from you in the first place!

R.

### CODE REVIEW

**Comment by robinbowes** [comment]
Hmmm, I just committed a change to rename mysql-agent to mysql-snmp throughout the code and it appears to have been added to this pull request.

**Comment by robinbowes** [comment]
Perhaps I should add that the name change was suggested by Ken:

"What is up with the name for this? It is called both "mysql-agent"
and "mysql-snmp". I'd prefer "mysql-snmp" everywhere, since that name
will be more likely to be accepted into Fedora
(http://fedoraproject.org/wiki/Packaging:NamingGuidelines)."

**Comment by masterzen** [comment]
At last, I found some time to merge these changes!
Thanks!

**Comment by robinbowes** [comment]
Woot! :)

**Pull request closed without merging**
